# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				panda = true
				ravager = true
				bee = true
				axolotl = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				pig = true
				slime = true
				pillager = true
				iron_golem = true
				skeleton = true
				llama = true
				area_effect_cloud = true
				bat = true
				cat = true
				rabbit = true
				zombie = true
				armor_stand = true
				drowned = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				illusioner = true
				item = true
				potion = true
				turtle = true
				wolf = true
				villager = true
				salmon = true
				zombie_villager = true
				ocelot = true
				horse = true
				vindicator = true
				painting = true
				evoker = true
				cave_spider = true
				glow_squid = true
				cod = true
				squid = true
				spider = true
				parrot = true
				creeper = true
				enderman = true

			[light_sources.settings.entities.bewitchment]
				ghost = true

			[light_sources.settings.entities.unvotedandshelved]
				glare = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				reindeer = true
				jellyfish = true
				goose = true
				songbird = true
				eel_freshwater = true
				boar = true
				dragonfly = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				shark = true
				piranha = true
				nautilus = true
				moose = true
				badger = true
				squirrel = true
				brownbear = true
				horseshoecrab = true
				turkey = true
				coyote = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				badlands_creeper = true
				dripstone_creeper = true
				jungle_creeper = true
				cave_creeper = true
				spruce_creeper = true

			[light_sources.settings.entities.elementalcreepers]
				earth_creeper = true
				electric_creeper = true
				light_creeper = true

			[light_sources.settings.entities.golemsgalore]
				quartz_golem = true
				obsidian_golem = true
				laser_golem = true

			[light_sources.settings.entities.terrarianslimes]
				black_slime = true
				green_slime = true
				jungle_slime = true
				red_slime = true
				yellow_slime = true
				mother_slime = true
				blue_slime = true

			[light_sources.settings.entities.mythicmounts]
				direwolf = true
				dragon = true
				griffon = true

			[light_sources.settings.entities.promenade]
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.aqupd]
				grizzly_bear = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				dairy_cow = true
				pink_footed_pig = true
				flecked_sheep = true
				cream_cow = true
				midnight_chicken = true
				umbra_cow = true
				skeleton_wolf = true
				rainbow_sheep = true
				mottled_pig = true
				gold_crested_chicken = true
				bold_striped_rabbit = true
				muddy_pig = true
				freckled_rabbit = true
				sooty_pig = true
				patched_sheep = true
				stormy_chicken = true
				horned_sheep = true
				rocky_sheep = true
				pinto_cow = true
				fuzzy_sheep = true
				albino_cow = true
				fancy_chicken = true
				jolly_llama = true
				inky_sheep = true
				skewbald_chicken = true

			[light_sources.settings.entities.adventurez]
				deer = true
				amethyst_golem = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

