# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				cow = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				rabbit = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				salmon = true
				wither_skeleton = true
				ocelot = true
				horse = true
				vindicator = true
				evoker = true
				glow_squid = true
				squid = true
				parrot = true
				creeper = true
				enderman = true
				chicken = true
				ravager = true
				donkey = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				cat = true
				zombie = true
				sheep = true
				player = true
				illusioner = true
				pufferfish = true
				potion = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.vanilla_degus]
				degu = true

			[light_sources.settings.entities.bewitchment]
				ghost = true
				werewolf = true
				raven = true
				owl = true
				snake = true

			[light_sources.settings.entities.unvotedandshelved]
				glare = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				reindeer = true
				jellyfish = true
				octopus = true
				goose = true
				songbird = true
				badgerdirt = true
				eel_freshwater = true
				boar = true
				dragonfly = true
				whale = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				shark = true
				flying_fish = true
				piranha = true
				barracuda = true
				nautilus = true
				moose = true
				tarantula = true
				badger = true
				squirrel = true
				brownbear = true
				walrus = true
				horseshoecrab = true
				turkey = true
				coyote = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				spruce_creeper = true
				hills_creeper = true

			[light_sources.settings.entities.elementalcreepers]
				hydrogen_creeper = true
				illusion_creeper = true
				earth_creeper = true
				reverse_creeper = true
				electric_creeper = true
				light_creeper = true
				fire_creeper = true
				dark_creeper = true

			[light_sources.settings.entities.golemsgalore]
				quartz_golem = true
				obsidian_golem = true
				laser_golem = true

			[light_sources.settings.entities.terrarianslimes]
				black_slime = true
				sand_slime = true
				green_slime = true
				jungle_slime = true
				red_slime = true
				yellow_slime = true
				mother_slime = true
				blue_slime = true

			[light_sources.settings.entities.mythicmounts]
				courierbird = true
				direwolf = true
				dragon = true
				griffon = true
				archelon = true
				geckotoalizard = true

			[light_sources.settings.entities.promenade]
				duck = true
				lush_creeper = true

			[light_sources.settings.entities.aqupd]
				caracal = true
				grizzly_bear = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				muddy_foot_rabbit = true
				dairy_cow = true
				pink_footed_pig = true
				flecked_sheep = true
				cream_cow = true
				midnight_chicken = true
				umbra_cow = true
				skeleton_wolf = true
				rainbow_sheep = true
				mottled_pig = true
				gold_crested_chicken = true
				bold_striped_rabbit = true
				muddy_pig = true
				freckled_rabbit = true
				wooly_cow = true
				amber_chicken = true
				sooty_pig = true
				patched_sheep = true
				jumbo_rabbit = true
				stormy_chicken = true
				horned_sheep = true
				harelequin_rabbit = true
				rocky_sheep = true
				pinto_cow = true
				cookie_cow = true
				fuzzy_sheep = true
				albino_cow = true
				fancy_chicken = true
				jolly_llama = true
				inky_sheep = true
				sunset_cow = true
				skewbald_chicken = true
				pale_pig = true

			[light_sources.settings.entities.adventurez]
				deer = true
				iguana = true
				amethyst_golem = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true

			[light_sources.settings.entities.snowpig]
				snow_pig = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

